### ISSUE TITLE
How to purchase the CXL-DRAM?

### ISSUE THREAD

**Issue by Twelvecat** [OpenMPDK/SMDK#21]
I noticed that Samsung announced the latest 512GB CXL-DRAM. But there is no way to buy it. How do I contact? Thanks.

**Comment by junhyeok-im** [comment]
Twelvecat, 
Thanks for your interest in SMDK and Samsung's MXP product. 
Since I (and my team) am in SMDK SW development side, please understand that I cannot answer to your question.

Please send me a personal email to the address below:
     junhyeok.im@samsung.com
then I will make connection to the right contact point. 

Thanks!

Junhyeok Im.

**Comment by junhyeok-im** [comment]
I forwared this inquiry to right department/member of Samsung, so I am going to close this issue.
