### ISSUE TITLE
How to use SMDK with QEMU 

### ISSUE THREAD

**Issue by Tom-CaoZH** [OpenMPDK/SMDK#23]
Because I do not have the CXL device and I have discovered that QEMU enables CXL 2.0 emulation. Therefore, I am interested in using SMDK with QEMU. Additionally, I came across a previous issue (https://github.com/OpenMPDK/SMDK/issues/15) where errors were encountered while running SMDK on QEMU. I would like to inquire if there is a practical and reliable method to successfully run SMDK on QEMU.

**Comment by 812231487** [comment]
I also have this problem

**Comment by KyungsanKim** [comment]
Hi all, sorry for late reply.
We are going to provide a patch set to support SMDK v1.5 on QEMU in a couple of weeks.
The patch will allow most of SMDK functions - userspace plugins(library, cli, BM, testcases) and OS interfaces(swap and cache).
However, among the three grouping functions - group,zone,noop, - group-noop would only be supported.
Because we are preparing a migration plan aligning with vanilla linux.

**Comment by Tom-CaoZH** [comment]
@KyungsanKim Thank you for your reply!

**Comment by KyungsanKim** [comment]
Hi all,
Please find https://github.com/OpenMPDK/SMDK/releases/tag/smdk_v1.5.1 

Hope it helps you. Let me know any incoming inquery :)

**Comment by jhk5361** [comment]
Dear @KyungsanKim,

I'm delighted to hear about recent developments in QEMU emulation.
I have a couple of questions.

Does the emulator incorporate "performance emulation" features for CXL-DRAM and other CXL devices? I'm interested in expecting and estimating the performance of CXL DRAM without the actual hardware.

If not, does this version of QEMU offer additional functionalities such as registration, mailbox support, or other non-device performance emulation features?
